export const STRINGS = {
    create_account:'Create Account',
    Signin:'Sign In',
    toc_text:`By tapping ‘Sign In/Create Account you agree to our Terms & Conditions & Privacy Policy`,
    skip:'Skip',
    intro:'Let’s begin with a quick introduction.',
    username:'Username',
    p_h_username:'Enter a username',
    firstname:'First Name',
    p_h_firstname:'Enter your first name',
    gender:'Gender',
    continue:'Continue',
    select:"Select",
    email:'Email',
    p_h_email:'Enter email',
    phone:'Phone',
    p_h_phone:'Enter your phone number',
    birthday:'When’s your birthday?',
    birthInfo:'Enter your birthday to ensure accurate age filters and better matches. Your birthday will not be displayed publicly.',
    verifyText:'Verify your',
    phonenumber:'phone number',
    emailaddress:'email address',
    smssentText:'We’ve sent an SMS with an activation code to your',
    emailotpsentText:'We’ve sent an email with an activation code to your',
    verify:'Verify',
    resendcode:'I didn’t receive a code',
    resend:'Resend',
    sendagain:'Send code again',
    otperrorText:'Wrong code, please try again',
    continuesingup:'Continue sign up',
    welcome:'Welcome to Loktin!',
    welcomsubText:'We’re glad to have you. Let’s finalize some information.',
    addcontact:'Add a trusted contact',
    communityintro:'Do you support any causes or communities?',
    communitysub:'Pick up to five causes that are especially meaningful to you.',
    cause_community:'Causes and communities',
    interestIntro:`What about your\ninterests?`,
    intertestSub:`Share what you’re interested in! We’ll use this to\nbetter tailor your experience.`,
    myinterest:'My Interest',
    interestsearchplaceholder:'What are you into?',
    profileIntro:'Make your profile yours!',
    profileSub:'Add up to 6 photos. Whether it’s a photo with friends, doing something you love, or just being yourself.',
    phonequeston:`What’s your phone number?`,
    emailquestion:`What’s your email?`,
    phonesenttext:`By entering your phone number you consent to receive a one-time passcode for authentication. Message and data rates may apply.`,
    emailsenttext:`We'll send you an email to verify it's really you.`,
    signinwith:`Sign in with `,
    facenotfind:`Oops! We couldn’t find a face in any of your photos. Try again with better lighting or a clearer angle`,
    leave:`Leave`,
}